---
title: "Alaska"
author: "Grace Lewin"
date: "10/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(metajam)
library(tidyverse)
library(here)
```



metajam documentation: https://nceas.github.io/metajam/articles/dataset-single.html


## Download the data

Data package: https://doi.org/10.5063/F1N58JPP

```{r, error = TRUE, echo = FALSE, message=FALSE, warning=FALSE}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A7fc6f6db-c5ea-426a-a743-1f2edafb43b8"
path <- here()

metajam::download_d1_data(data_url = data_url, path = path)
```


```{r, include = FALSE}
#data$attribute_metadata %>% view() # shows metadata
#data$data %>% view() # shows actual data
```



```{r, include=FALSE}
data_path <- here("doi_10.5063_F1CJ8BPH__household_language__csv")
```

```{r, include=FALSE}
hh_list<- metajam::read_d1_files(data_path)
```

```{r, include = FALSE}
hh_list$attribute_metadata

# get the datafrqame about housefold
hh_data <- hh_list$data

# get the attribute (columns) metadata
hh_att_metadata <- hh_list$summary_metadata

english <- hh_data %>% 
  filter(Year >= 2009) %>% 
  mutate(percent_english = (speak_only_english/total)*100) %>% 
  group_by(Year) %>% 
  summarise(avg_perc_english = mean(percent_english, na.rm = TRUE))
 
```


```{r, echo = FALSE}
ggplot(data = english, aes(x = Year, y = avg_perc_english)) +
  geom_line() +
  labs(y = "Avg percentage of households speaking only English",
       title = "Average percentage of Alaskan households speaking only English")
```

